using System.ComponentModel.DataAnnotations;

namespace DOAN.ViewModel
{
    public class TaiKhoanChuyenDungViewModel
    {
        // Customer info
        public string CustomerName { get; set; }
        public string PhoneNumber { get; set; }
        public string IdentityNumber { get; set; }

        // Deposit account info
        public string Branch { get; set; } = "Bình Gia Branch";
        public string AccountType { get; set; }
        public int? Term { get; set; }  // in months
        public DateTime OpenDate { get; set; }
        public decimal InitialDeposit { get; set; }
        public decimal InterestRate { get; set; }

        // Additional info for specialized account creation (if needed)
        public string InterestReceiveMethod { get; set; }  // e.g., "taquay" or "mochuyendung"
        public string AccountHolderDeposit { get; set; }     // Name for specialized account
        public string AccountNumberDeposit { get; set; }       // (Optional: generated by JS)
    }
}
